### ISSUE TITLE
Install issue with kbr5 on Macosx

### ISSUE THREAD

**Issue by jontonsoup** [sdelements/lets-chat-kerberos#1]
I'm new to node, so I'm not sure if this is fixable in the lets-chat-kerberos repo or not. 

I'm getting an error on mac Yosemite when I run `npm install lets-chat-kerberos`. 

I have xcode and command line tools installed. 

node -v
v0.12.0

Here is the output: 

```
2260 verbose linkStuff [ false,
2260 verbose linkStuff   false,
2260 verbose linkStuff   false,
2260 verbose linkStuff   '/Users/danieldaks1/src/letschat/node_modules/lets-chat-kerberos/node_modules/passport-kerberos/node_modules/node-krb5/node_modules/node-gyp/node_modules/mkdirp/node_modules' ]
2261 info linkStuff minimist@0.0.8
2262 verbose linkBins minimist@0.0.8
2263 verbose linkMans minimist@0.0.8
2264 verbose rebuildBundles minimist@0.0.8
2265 info postinstall fstream@0.1.31
2266 info install minimist@0.0.8
2267 info postinstall minimist@0.0.8
2268 verbose unlock done using /Users/danieldaks1/.npm/_locks/fstream-7b3158eabfbb53d0.lock for /Users/danieldaks1/src/letschat/node_modules/lets-chat-kerberos/node_modules/passport-kerberos/node_modules/node-krb5/node_modules/node-gyp/node_modules/fstream
2269 verbose unlock done using /Users/danieldaks1/.npm/_locks/minimist-a3bbb6d35ce1b155.lock for /Users/danieldaks1/src/letschat/node_modules/lets-chat-kerberos/node_modules/passport-kerberos/node_modules/node-krb5/node_modules/node-gyp/node_modules/mkdirp/node_modules/minimist
2270 verbose about to build /Users/danieldaks1/src/letschat/node_modules/lets-chat-kerberos/node_modules/passport-kerberos/node_modules/node-krb5/node_modules/node-gyp/node_modules/mkdirp
                       ~~~~~ ^
../src/krb5.cc:111:30: error: no member named 'New' in 'v8::String'
                return scope.Close(String::New("wrong arguments"));
                                   ~~~~~~~~^
../src/krb5.cc:116:51: error: no member named 'AsciiValue' in 'v8::String'
        authStruct->principal = new std::string(*String::AsciiValue(Local<String>::Cast(args[0])));
                                                 ~~~~~~~~^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
8 warnings and 20 errors generated.
make: *** [Release/obj.target/krb5/src/krb5.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Darwin 14.0.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/danieldaks1/src/letschat/node_modules/lets-chat-kerberos/node_modules/passport-kerberos/node_modules/node-krb5
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
npm ERR! Darwin 14.0.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "lets-chat-kerberos"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! node-krb5@0.0.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-krb5@0.0.5 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the node-krb5 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-krb5
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/danieldaks1/src/letschat/npm-debug.log
```

Thanks!

**Comment by sibartlett** [comment]
Weird! We use Yosemite and Kerberos here. 

In the stack trace, I see it might be related to the V8 version shipped with node 0.12: `error: no member named 'AsciiValue' in 'v8::String'`

We've been using node 0.10 - haven't tested node 0.12 yet.

**Comment by sibartlett** [comment]
We've opened an [issue](https://github.com/qesuto/node-krb5/issues/8) on the node-krb5 project.

In the mean time, node 0.10 is required, and we'll add that to the documentation.

**Comment by hhaidar** [comment]
Yea I'd just grab nvm and switch to 0.10 for now.

**Comment by jontonsoup** [comment]
@hhaidar / @sibartlett thanks! I'll take a look at node .10 now.

**Comment by jontonsoup** [comment]
As an update, I'm using node v0.10.36, and still getting errors on foreman start. 

```
14:52:51 web.1  | started with pid 63587
14:52:51 web.1  |
14:52:51 web.1  | > lets-chat@0.3.0 prestart /Users/danieldaks1/src/letschat
14:52:51 web.1  | > migroose
14:52:51 web.1  |
14:52:51 web.1  | dyld: lazy symbol binding failed: Symbol not found: _node_module_register
14:52:51 web.1  |   Referenced from: /Users/danieldaks1/src/letschat/node_modules/mongoose/node_modules/mongodb/node_modules/bson/build/Release/bson.node
14:52:51 web.1  |   Expected in: dynamic lookup
14:52:51 web.1  |
14:52:51 web.1  | dyld: Symbol not found: _node_module_register
14:52:51 web.1  |   Referenced from: /Users/danieldaks1/src/letschat/node_modules/mongoose/node_modules/mongodb/node_modules/bson/build/Release/bson.node
14:52:51 web.1  |   Expected in: dynamic lookup
14:52:51 web.1  |
14:52:52 web.1  | terminated by SIGTRAP
14:52:52 system | sending SIGTERM to all processes
```

**Comment by sibartlett** [comment]
@jontonsoup when you switched to node 0.10.36, did you `rm -rf node_modules`? If not, try that and `npm install` again.

Edit: Added `-rf` flag.

**Comment by jontonsoup** [comment]
@sibartlett thanks! I'm now getting this error: 

```
> node-expat@2.3.5 install /Users/danieldaks1/src/letschat/node_modules/node-xmpp-core/node_modules/ltx/node_modules/node-expat
> node-gyp rebuild

  CC(target) Release/obj.target/expat/deps/libexpat/lib/xmlparse.o
  CC(target) Release/obj.target/expat/deps/libexpat/lib/xmltok.o
../deps/libexpat/lib/xmltok.c:471:1: warning: missing field 'isName2' initializer [-Wmissing-field-initializers]
};
^
../deps/libexpat/lib/xmltok.c:484:1: warning: missing field 'isName2' initializer [-Wmissing-field-initializers]
};
^
../deps/libexpat/lib/xmltok.c:504:1: warning: missing field 'isName2' initializer [-Wmissing-field-initializers]
};
^
../deps/libexpat/lib/xmltok.c:517:1: warning: missing field 'isName2' initializer [-Wmissing-field-initializers]
};
^
../deps/libexpat/lib/xmltok.c:730:1: warning: missing field 'isName2' initializer [-Wmissing-field-initializers]
};
^
../deps/libexpat/lib/xmltok.c:749:1: warning: missing field 'isName2' initializer [-Wmissing-field-initializers]
};
^
../deps/libexpat/lib/xmltok.c:762:1: warning: missing field 'isName2' initializer [-Wmissing-field-initializers]
};
^
../deps/libexpat/lib/xmltok.c:775:1: warning: missing field 'isName2' initializer [-Wmissing-field-initializers]
};
^
../deps/libexpat/lib/xmltok.c:871:1: warning: missing field 'isName2' initializer [-Wmissing-field-initializers]
};
^
../deps/libexpat/lib/xmltok.c:890:1: warning: missing field 'isName2' initializer [-Wmissing-field-initializers]
};
^
10 warnings generated.
  CC(target) Release/obj.target/expat/deps/libexpat/lib/xmlrole.o
  LIBTOOL-STATIC Release/libexpat.a
  CXX(target) Release/obj.target/node_expat/node-expat.o
../node-expat.cc:42:9: warning: 'NanRawString' is deprecated [-Wdeprecated-declarations]
        NanRawString(args[0], Nan::ASCII, NULL, encoding, 32, 0);
        ^
../node_modules/nan/nan.h:1936:33: note: 'NanRawString' has been explicitly marked deprecated here
NAN_DEPRECATED NAN_INLINE void* NanRawString(
                                ^
../node-expat.cc:150:9: warning: 'NanRawString' is deprecated [-Wdeprecated-declarations]
        NanRawString(args[0], Nan::ASCII, NULL, encoding, 32, 0);
        ^
../node_modules/nan/nan.h:1936:33: note: 'NanRawString' has been explicitly marked deprecated here
NAN_DEPRECATED NAN_INLINE void* NanRawString(
                                ^
../node-expat.cc:223:9: warning: 'NanRawString' is deprecated [-Wdeprecated-declarations]
        NanRawString(args[0], Nan::ASCII, NULL, encoding, 32, 0);
        ^
../node_modules/nan/nan.h:1936:33: note: 'NanRawString' has been explicitly marked deprecated here
NAN_DEPRECATED NAN_INLINE void* NanRawString(
                                ^
3 warnings generated.
  SOLINK_MODULE(target) Release/node_expat.node
  SOLINK_MODULE(target) Release/node_expat.node: Finished
mongoose-unique-validator@0.4.1 node_modules/mongoose-unique-validator
```

**Comment by sibartlett** [comment]
@jontonsoup I get those warnings, you may ignore them :)

**Comment by chakrihacker** [comment]
sudo npm start

> lets-chat@0.3.3 prestart /home/chakrihacker/Downloads/lets-chat-master
> migroose

/home/chakrihacker/Downloads/lets-chat-master/migroose.js:10
            if (err) { throw err; }
                             ^
Error: failed to connect to [localhost:27017]
    at null.<anonymous> (/home/chakrihacker/Downloads/lets-chat-master/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:555:74)
    at emit (events.js:106:17)
    at null.<anonymous> (/home/chakrihacker/Downloads/lets-chat-master/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:150:15)
    at emit (events.js:98:17)
    at Socket.<anonymous> (/home/chakrihacker/Downloads/lets-chat-master/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection.js:534:10)
    at Socket.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:419:13)

npm ERR! lets-chat@0.3.3 prestart: `migroose`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the lets-chat@0.3.3 prestart script.
npm ERR! This is most likely a problem with the lets-chat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     migroose
npm ERR! You can get their info via:
npm ERR!     npm owner ls lets-chat
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.13.0-32-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! cwd /home/chakrihacker/Downloads/lets-chat-master
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/chakrihacker/Downloads/lets-chat-master/npm-debug.log
npm ERR! not ok code 0

**Comment by chakrihacker** [comment]
help me for above error thanks

**Comment by sibartlett** [comment]
@chakrihacker you need MongoDB to be running.

**Comment by chakrihacker** [comment]
how to install kerberos in docker

**Comment by sibartlett** [comment]
@jontonsoup can I close this ticket?

**Comment by jontonsoup** [comment]
Yup!

Thanks,

Jon

Jonathan Friedman

https://www.linkedin.com/pub/jonathan-friedman/2b/b10/630
